{{- if .Values.alertmanager.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.alertmanager.name }}
  labels:
    app_name: {{ .Values.alertmanager.name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
spec:
  storageClassName: {{ .Values.alertmanager.persistentVolume.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end -}}