apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-expiry-exporter
  labels:
    app_name: domain-expiry-exporter
    app_version: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app_name: domain-expiry-exporter
  template:
    metadata:
      labels:
        app_name: domain-expiry-exporter
        app_version: {{ .Values.image.tag }}
    spec:
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: domain-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9222
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9222
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
