{{ $root := . }}
{{- range .Values.thanos.store.stores }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app_name: thanos
    app_version: {{ $root.Values.thanos.image.tag | quote }}
  name: "thanos-s3-config-{{ .name}}"
data:
  s3.yaml: |
    type: S3
    config:
      bucket: {{ .bucket }}
      endpoint: {{ .endpoint }}
      encrypt_sse: {{ .encryptSse }}
      signature_version2: false
      http_config:
        idle_conn_timeout: 0s
{{- end }}
