env: test

# https://github.com/prometheus/alertmanager
alertmanager:
  name: alertmanager

  image:
    repository: docker.io
    name: prom/alertmanager
    tag: v0.19.0
    pullPolicy: IfNotPresent

  # Setting this to blank string so that it is not used by default.
  imagePullSecretName: ""

  extraArgs: {}

  nodeSelector: {}

  tolerations: []

  persistentVolume:
    enabled: false
    storageClassName: general-purpose-retain
    mountPath: /data

  podAnnotations: {}

  replicaCount: 1

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  service:
    annotations: {}

  slack:
    apiUrl: ""
    channel: ""   # Please include the '#' as well.

  ingress:
    hostname: alertmanager-dev

# https://github.com/kubernetes/git-sync
gitSync:
  git:
    branch: ""
    repo: ""
  image:
    name: git-sync
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io
    tag: v3.1.1

# https://github.com/prometheus/prometheus
server:
  name: prometheus

  image:
    repository: docker.io
    name: prom/prometheus
    tag: 2.17.2
    pullPolicy: IfNotPresent

  # Setting this to blank string so that it is not used by default.
  imagePullSecretName: ""

  replicas: 2

  extraArgs: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  podAnnotations: {}

  ingress:
    hostname: ""

  # This should be appx 70% of server.persistentVolume.size to allow for ~20% for WAL and ~10% headroom
  # - see here for more: https://prometheus.io/docs/prometheus/2.13/storage/#operational-aspects
  retentionSize: 700GB

  persistentVolume:
    size: 1Ti
    storageClassName: general-purpose-retain
    accessModes: ReadWriteOnce

# https://github.com/thanos-io/thanos
thanos:

  image:
    repository: docker.io
    name: bitnami/thanos
    tag: 0.12.2-scratch-r3
    pullPolicy: IfNotPresent

  sidecar:
    extraArgs: {}

  store:
    resources: {}
    stores:
      - name: dev
        bucket: "thanos"
        endpoint: "s3.eu-west-2.amazonaws.com"
        encryptSse: false
        replicas: 1
