env: dev

istio:
  enabled: false

scrape:
  kubeControllerManagerService:
    enabled: true
  kubeSchedulerService:
    enabled: true

# https://github.com/kubernetes/git-sync
gitSync:

  git:
    branch: ""
    repo: ""

  image:
    name: git-sync
    pullPolicy: IfNotPresent
    repository: eu.gcr.io/google-containers
    tag: v3.1.1

# https://github.com/prometheus/prometheus
server:
  name: prometheus

  image:
    repository: docker.io
    name: prom/prometheus
    tag: 2.17.2
    pullPolicy: IfNotPresent

  # Setting this to blank string so that it is not used by default.
  imagePullSecretName: ""

  replicas: 2

  extraArgs: {}
  resources: {}

  gitSync:
    resources: {}

  nodeSelector: {}
  tolerations: []
  podAnnotations: {}

  ingress:
    hostname: ""

  persistentVolume:
    size: 1Ti
    storageClassName: general-purpose-retain
    accessModes: ReadWriteOnce

# This value should not be set high without consideration.
# Thanos is our long term view on data.
  retentionTime: 7d

  rbac:
    nameOverride: ""

# https://github.com/thanos-io/thanos
thanos:
  enabled: true

  image:
    repository: docker.io
    name: bitnami/thanos
    tag: 0.12.2-scratch-r3
    pullPolicy: IfNotPresent

  sidecar:

    extraArgs: {}

    resources: {}

  store:
    resources: {}
    stores:
      - name: dev
        bucket: "thanos"
        endpoint: "s3.eu-west-2.amazonaws.com"
        encryptSse: false
        replicas: 1
