# https://github.com/kubernetes/git-sync
gitSync:

  git:
    branch: ""
    repo: ""

  image:
    name: git-sync
    pullPolicy: IfNotPresent
    repository: eu.gcr.io/google-containers
    tag: v3.1.1

# https://github.com/alertmanager/alertmanager
alertmanager:
  name: alertmanager

  image:
    repository: docker.io
    name: prom/alertmanager
    tag: v0.19.0
    pullPolicy: IfNotPresent

  # Setting this to blank string so that it is not used by default.
  imagePullSecretName: ""

  extraArgs: {}

  nodeSelector: {}

  tolerations: []

  podAnnotations: {}

  replicaCount: 1

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  gitSync:
    resources: {}

  service:
    annotations: {}

  slack:
    apiUrl: ""
    channel: ""   # Please include the '#' as well.

  ingress:
    hostname: alertmanager-dev
