apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  labels:
    app_name: {{ .Values.server.name }}
    app_version: {{ .Values.server.image.tag | quote }}
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: prom-http
    name: http-prometheus
  selector:
    app_name: {{ .Values.server.name }}
