apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app_name: {{ .Values.alertmanager.name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
  name: {{ .Values.alertmanager.name }}