apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.alertmanager.name }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
{{- with .Values.alertmanager.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.alertmanager.ingress.tls }}
  tls:
  {{- range .Values.alertmanager.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.alertmanager.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.alertmanager.name }}
          servicePort: 80
