apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app_name: {{ .Values.alertmanager.name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
  name: {{ .Values.alertmanager.name }}
spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  selector:
    matchLabels:
      app_name: {{ .Values.alertmanager.name }}
  template:
    metadata:
      annotations:
        {{- if .Values.alertmanager.podAnnotations }}
{{ toYaml .Values.alertmanager.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app_name: {{ .Values.alertmanager.name }}
        app_version: {{ .Values.alertmanager.image.tag | quote }}
    spec:
      {{- if .Values.alertmanager.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.alertmanager.imagePullSecretName }}
      {{- end }}
      serviceAccountName: {{ .Values.alertmanager.name }}
{{- if .Values.alertmanager.tolerations }}
      tolerations:
{{ toYaml .Values.alertmanager.tolerations | indent 8 }}
    {{- end }}
      priorityClassName: mettle-cluster-critical
      initContainers:

        - name: init
          image: busybox:1-musl
          command: ['/bin/chown', 'nobody:nogroup', '/data']
          volumeMounts:
          - name: storage-volume
            mountPath: /data

        - name: wait-deploy-key
          image: busybox:1-musl
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'counter=0; until [ "$counter" -ge 30 ]; do if [ -f /etc/git-secret/ssh ]; then exit 0; else echo "Waiting for git deploy key" && sleep 1 && counter=$((counter+1)); fi; done; exit 1;']
          volumeMounts:
          - mountPath: /etc/git-secret
            name: git-secret

        - name: git-sync-init
          image: "{{ .Values.gitSync.image.repository }}/{{ .Values.gitSync.image.name }}:{{ .Values.gitSync.image.tag }}"
          imagePullPolicy: "{{ .Values.gitSync.image.pullPolicy }}"
          args:
           - "-branch={{ .Values.gitSync.git.branch }}"
           - "-depth=1"
           - "-one-time=true"
           - "-repo=git@github.com:{{ .Values.gitSync.git.repo }}"
           - "-root=/etc/alertmanager-shared"
           - "-ssh"
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: config-shared
            mountPath: /etc/alertmanager-shared
          - name: git-secret
            mountPath: /etc/git-secret

      containers:

        - name: {{ .Values.alertmanager.name }}
          image: {{ .Values.alertmanager.image.repository }}/{{ .Values.alertmanager.image.name }}:{{ .Values.alertmanager.image.tag }}
          imagePullPolicy: "{{ .Values.alertmanager.image.pullPolicy }}"
          args:
            - --config.file=/etc/alertmanager-shared/monitoring-resources/{{ .Values.env }}/alertmanager/alertmanager.yml
            - --storage.path=/data
          {{- range $key, $value := .Values.alertmanager.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
{{ toYaml .Values.alertmanager.resources | indent 12 }}
          volumeMounts:
            - name: config-shared
              mountPath: /etc/alertmanager-shared
            - name: storage-volume
              mountPath: "/data"

        - name: git-sync
          image: "{{ .Values.gitSync.image.repository }}/{{ .Values.gitSync.image.name }}:{{ .Values.gitSync.image.tag }}"
          imagePullPolicy: "{{ .Values.gitSync.image.pullPolicy }}"
          args:
           - "-branch={{ .Values.gitSync.git.branch }}"
           - "-depth=1"
           - "-max-sync-failures=240"
           - "-repo=git@github.com:{{ .Values.gitSync.git.repo }}"
           - "-root=/etc/alertmanager-shared"
           - "-ssh"
           - "-wait=30"
           - "--webhook-url=http://localhost:9093/-/reload"
          securityContext:
            runAsUser: 0
{{ if .Values.alertmanager.gitSync.resources }}
          resources:
{{ toYaml .Values.alertmanager.gitSync.resources | indent 12 }}
{{ end }}
          volumeMounts:
          - name: config-shared
            mountPath: /etc/alertmanager-shared
          - name: git-secret
            mountPath: /etc/git-secret

{{- if .Values.alertmanager.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.alertmanager.nodeSelector | indent 8 }}
{{- end }}
      volumes:
        - name: config-shared
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 256
        - name: storage-volume
          emptyDir: {}
